version: '3'
volumes:
  free-note-api_sync_volume:
services:
  free-note-api:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
    env_file: .env
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - free-note-api_sync_volume:/free-note-back
    ports:
      - "3000:3000"
    links:
      - free-note-db
    depends_on:
      - free-note-db
  free-note-db:
    image: mysql:5.7
    environment: 
      TZ: Asia/Tokyo
    env_file: .env_db
    ports:
      - "3307:3306"